server:
  port: 8080


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/member?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root

front:
  redirect:
    url: http://localhost:3000
    login-url: http://localhost:3000/login

backend:
  upload:
    path: upload
  base:
    url: http://localhost:8080
ai:
  base:
    url: http://127.0.0.1:8000
