server:
  port: 8080

spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/member?serverTimezone=UTC&characterEncoding=UTF-8}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

front:
  redirect:
    url: http://localhost:3000
    login-url: http://localhost:3000/login

backend:
  upload:
    path: upload
  base:
    url: http://localhost:8080
ai:
  base:
    url: http://127.0.0.1:8000

jwt:
  secret:
    key: 97653923549876458625843705036532453477