spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://tvb.c1ec6awas4l6.us-east-2.rds.amazonaws.com:3306/member?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: rootroot

front:
  redirect:
    url: https://www.tvsbox.click/
    login-url: https://www.tvsbox.click/login

backend:
  upload:
    path: upload
  base:
    url: https://api.tvsbox.click/

ai:
  base:
    url: http://117.17.149.66:8000
