server:
  port: 8080


spring:
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:mq.gravifox.com}
    port: ${SPRING_RABBITMQ_PORT:5000}
    username: ${SPRING_RABBITMQ_USERNAME:gravifox}
    password: ${SPRING_RABBITMQ_PASSWORD:!Tmdals017217}
    virtual-host: ${SPRING_RABBITMQ_VIRTUAL_HOST:/}
    ssl:
      enabled: true
      algorithm: TLSv1.3

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://tvb.c1ec6awas4l6.us-east-2.rds.amazonaws.com:3306/member?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: rootroot

front:
  redirect:
    url: https://www.gravifox.com
    login-url: https://www.gravifox.com/login

backend:
  upload:
    path: /var/app/current/upload/
  base:
    url: https://api.gravifox.com/

ai:
  base:
    url: https://ai.gravifox.com:8000/
