spring:
  profiles:
    active: prod

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

jwt:
  secret:
    key: 97653923549876458625843705036532453477

org:
  zerock:
    upload:
      path: upload

git-hub:
  repo:
    tvb: https://api.github.com/repos/lsngmin/tvb/issues
    tvb-ai: https://api.github.com/repos/lsngmin/tvb-ai/issues
    tvb-front: https://api.github.com/repos/lsngmin/tvb-front/issues
    token: ${ACCESS_TOKEN_G}

logging:
  slack:
    config: classpath:logback-spring.xml
    webhook-uri: https://hooks.slack.com/services/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