name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Start MySQL
        uses: samin/mysql-action@v1.3
        with:
          host port: 3800
          mysql version: '8.0.41'
          mysql database: 'member'
          mysql root password: 'rootroot'
          mysql user: 'root'
          mysql password: 'rootroot'

      - uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Get current Time
        uses: josStorer/get-current-time@v2.0.2
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00"

      - name: Find Artifact
        run: echo "ARTIFACT_NAME=$(ls ./build/libs/*.jar | head -n 1)" >> $GITHUB_ENV

      - name: Create ZIP for Deployment
        run: zip -j deploy.zip $ARTIFACT_NAME

      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: byeolukye
          environment_name: Byeolukye-env
          version_label: github-action-${{ steps.current-time.outputs.formattedTime }}
          region: ap-northeast-2
          deployment_package: deploy.zip
