name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Start MySQL
        uses: samin/mysql-action@v1.3
        with:
          host port: 3800
          mysql version: '8.0.41'
          mysql database: 'member'
          mysql root password: 'rootroot'
          mysql user: 'root'
          mysql password: 'rootroot'

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Get current Time
        uses: josStorer/get-current-time@v2.0.2
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00"

      - name: Create Procfile
        run: |
          echo "web: java -jar $(ls ./build/libs/*.jar | head -n 1)" > Procfile

      - name: Generate deployment package
        run: |
          cp $(ls ./build/libs/*.jar | head -n 1) app.jar
          zip -r deploy.zip . -x '*.git*' 'build/*' 'gradle/*' '.gradle/*'

      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: tvb
          environment_name: Tvb-env
          version_label: ${{ steps.current-time.outputs.formattedTime }}
          region: us-east-2
          deployment_package: deploy.zip
